/**
 * Preset definitions for NodeTerm appearance system.
 * Each preset bundles ALL appearance settings into a single selectable profile.
 *
 * Built-in presets are read-only. User presets are stored in localStorage under
 * 'nodeterm_user_presets' and can be created, renamed, and deleted.
 */

export const PRESET_STORAGE_KEY = 'nodeterm_user_presets';
export const ACTIVE_PRESET_STORAGE_KEY = 'nodeterm_active_preset';

/**
 * All localStorage keys that a preset captures and restores.
 */
export const PRESET_SETTINGS_KEYS = [
  // UI theme
  'ui_theme',
  // Tab theme, layout and animation
  'nodeterm_tab_theme',
  'nodeterm_tab_layout',
  'nodeterm_tab_reduced_motion',
  'nodeterm_tab_anim_speed',
  // Terminal themes per type
  'basicapp_terminal_theme',
  'localPowerShellTheme',
  'localLinuxTerminalTheme',
  'localDockerTerminalTheme',
  // Status bar themes per type
  'basicapp_statusbar_theme',
  'localPowerShellStatusBarTheme',
  'localLinuxStatusBarTheme',
  'localDockerStatusBarTheme',
  'localCygwinStatusBarTheme',
  // Status bar icon themes
  'basicapp_ssh_statusbar_icon_theme',
  'basicapp_powershell_statusbar_icon_theme',
  'basicapp_linux_statusbar_icon_theme',
  'basicapp_docker_statusbar_icon_theme',
  // Terminal fonts per type
  'basicapp_terminal_font_family',
  'basicapp_terminal_font_size',
  'basicapp_local_terminal_font_family',
  'basicapp_local_terminal_font_size',
  'nodeterm_linux_font_family',
  'nodeterm_linux_font_size',
  'nodeterm_docker_font_family',
  'nodeterm_docker_font_size',
  // Explorer / sidebar fonts
  'explorerFont',
  'explorerFontSize',
  'explorerColorTheme',
  'sidebarFont',
  'sidebarFontSize',
  'sidebarFontColor',
  // Cursor
  'nodeterm_cursor_style',
  'nodeterm_cursor_blink',
  // Icon themes and sizes
  'iconTheme',
  'iconThemeSidebar',
  'iconSize',
  'folderIconSize',
  'connectionIconSize',
  // Tree / session / action bar
  'nodeterm_tree_theme',
  'sessionActionIconTheme',
  'actionBarIconTheme',
  // Status bar misc
  'basicapp_statusbar_height',
];

/**
 * Built-in presets shipped with the application.
 * The "Mi Configuración" preset captures the common default setup.
 * Users can overwrite custom presets but not built-in ones.
 */
export const builtinPresets = [
  {
    id: 'default-dark',
    name: 'Default Dark',
    description: 'Tema oscuro clásico con interfaz Dark y terminal Default Dark',
    icon: '🌑',
    isBuiltin: true,
    settings: {
      ui_theme: 'Dark',
      nodeterm_tab_theme: 'default',
      nodeterm_tab_layout: 'default',
      basicapp_terminal_theme: 'Default Dark',
      localPowerShellTheme: 'Dark',
      localLinuxTerminalTheme: 'Dark',
      localDockerTerminalTheme: 'Default Dark',
      basicapp_statusbar_theme: 'Default Dark',
      localPowerShellStatusBarTheme: 'Monokai',
      localLinuxStatusBarTheme: 'Dracula',
      localDockerStatusBarTheme: 'One Dark',
      basicapp_terminal_font_family: '"Cascadia Code", monospace',
      basicapp_terminal_font_size: '14',
      basicapp_local_terminal_font_family: '"FiraCode Nerd Font", monospace',
      basicapp_local_terminal_font_size: '14',
      nodeterm_linux_font_family: 'Consolas',
      nodeterm_linux_font_size: '14',
      nodeterm_docker_font_family: 'Consolas',
      nodeterm_docker_font_size: '14',
      explorerFont: 'Segoe UI',
      explorerFontSize: '15',
      explorerColorTheme: 'Light',
      sidebarFont: 'Segoe UI',
      sidebarFontSize: '15',
      sidebarFontColor: '',
      nodeterm_cursor_style: 'bar',
      nodeterm_cursor_blink: 'true',
      iconTheme: 'nord',
      iconThemeSidebar: 'nord',
      iconSize: '20',
      folderIconSize: '20',
      connectionIconSize: '20',
      nodeterm_tree_theme: 'default',
      sessionActionIconTheme: 'modern',
      basicapp_statusbar_height: '32',
    }
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Tema Dracula completo: UI, terminal y status bar coordinados',
    icon: '🧛',
    isBuiltin: true,
    settings: {
      ui_theme: 'Dracula',
      nodeterm_tab_theme: 'default',
      nodeterm_tab_layout: 'default',
      basicapp_terminal_theme: 'Dracula',
      localPowerShellTheme: 'Dracula',
      localLinuxTerminalTheme: 'Dracula',
      localDockerTerminalTheme: 'Dracula',
      basicapp_statusbar_theme: 'Dracula',
      localPowerShellStatusBarTheme: 'Dracula',
      localLinuxStatusBarTheme: 'Dracula',
      localDockerStatusBarTheme: 'Dracula',
      basicapp_terminal_font_family: '"Fira Code", monospace',
      basicapp_terminal_font_size: '14',
      basicapp_local_terminal_font_family: '"FiraCode Nerd Font", monospace',
      basicapp_local_terminal_font_size: '14',
      nodeterm_linux_font_family: '"Fira Code", monospace',
      nodeterm_linux_font_size: '14',
      nodeterm_docker_font_family: '"Fira Code", monospace',
      nodeterm_docker_font_size: '14',
      explorerFont: 'Segoe UI',
      explorerFontSize: '15',
      explorerColorTheme: 'Dracula',
      sidebarFont: 'Segoe UI',
      sidebarFontSize: '15',
      sidebarFontColor: '',
      nodeterm_cursor_style: 'block',
      nodeterm_cursor_blink: 'true',
      iconTheme: 'dracula',
      iconThemeSidebar: 'dracula',
      iconSize: '20',
      folderIconSize: '20',
      connectionIconSize: '20',
      nodeterm_tree_theme: 'default',
      sessionActionIconTheme: 'modern',
      basicapp_statusbar_height: '32',
    }
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Tema Nord minimalista y frío, coordinado en todos los paneles',
    icon: '❄️',
    isBuiltin: true,
    settings: {
      ui_theme: 'Nord',
      nodeterm_tab_theme: 'default',
      nodeterm_tab_layout: 'default',
      basicapp_terminal_theme: 'Nord',
      localPowerShellTheme: 'Nord',
      localLinuxTerminalTheme: 'Nord',
      localDockerTerminalTheme: 'Nord',
      basicapp_statusbar_theme: 'Nord',
      localPowerShellStatusBarTheme: 'Nord',
      localLinuxStatusBarTheme: 'Nord',
      localDockerStatusBarTheme: 'Nord',
      basicapp_terminal_font_family: '"JetBrains Mono", monospace',
      basicapp_terminal_font_size: '14',
      basicapp_local_terminal_font_family: '"JetBrains Mono", monospace',
      basicapp_local_terminal_font_size: '14',
      nodeterm_linux_font_family: '"JetBrains Mono", monospace',
      nodeterm_linux_font_size: '14',
      nodeterm_docker_font_family: '"JetBrains Mono", monospace',
      nodeterm_docker_font_size: '14',
      explorerFont: 'Segoe UI',
      explorerFontSize: '15',
      explorerColorTheme: 'Nord',
      sidebarFont: 'Segoe UI',
      sidebarFontSize: '15',
      sidebarFontColor: '',
      nodeterm_cursor_style: 'underline',
      nodeterm_cursor_blink: 'false',
      iconTheme: 'nord',
      iconThemeSidebar: 'nord',
      iconSize: '20',
      folderIconSize: '20',
      connectionIconSize: '20',
      nodeterm_tree_theme: 'default',
      sessionActionIconTheme: 'modern',
      basicapp_statusbar_height: '32',
    }
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'Ambiente nocturno de Tokyo con neones suaves y tipografía moderna',
    icon: '🏙️',
    isBuiltin: true,
    settings: {
      ui_theme: 'Tokyo Night',
      nodeterm_tab_theme: 'default',
      nodeterm_tab_layout: 'default',
      basicapp_terminal_theme: 'Tokyo Night',
      localPowerShellTheme: 'Tokyo Night',
      localLinuxTerminalTheme: 'Tokyo Night',
      localDockerTerminalTheme: 'Tokyo Night',
      basicapp_statusbar_theme: 'Tokyo Night',
      localPowerShellStatusBarTheme: 'Tokyo Night',
      localLinuxStatusBarTheme: 'Tokyo Night',
      localDockerStatusBarTheme: 'Tokyo Night',
      basicapp_terminal_font_family: '"Cascadia Code", monospace',
      basicapp_terminal_font_size: '14',
      basicapp_local_terminal_font_family: '"Cascadia Code", monospace',
      basicapp_local_terminal_font_size: '14',
      nodeterm_linux_font_family: '"Cascadia Code", monospace',
      nodeterm_linux_font_size: '14',
      nodeterm_docker_font_family: '"Cascadia Code", monospace',
      nodeterm_docker_font_size: '14',
      explorerFont: 'Segoe UI',
      explorerFontSize: '15',
      explorerColorTheme: 'Light',
      sidebarFont: 'Segoe UI',
      sidebarFontSize: '15',
      sidebarFontColor: '',
      nodeterm_cursor_style: 'bar',
      nodeterm_cursor_blink: 'true',
      iconTheme: 'nord',
      iconThemeSidebar: 'nord',
      iconSize: '20',
      folderIconSize: '20',
      connectionIconSize: '20',
      nodeterm_tree_theme: 'default',
      sessionActionIconTheme: 'modern',
      basicapp_statusbar_height: '32',
    }
  },
];
